# Generated by Django 3.2.8 on 2022-01-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_processedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcustomer',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProcessedOrder',
        ),
    ]
