# Generated by Django 3.2.8 on 2022-01-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20220111_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
