# Generated by Django 3.2.8 on 2022-01-07 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220107_0055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.CharField(max_length=255)),
                ('product_image', models.ImageField(null=True, upload_to=vendors.models.upload_image_path)),
                ('Active', models.BooleanField(default=True)),
                ('featured_product', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Resell',
        ),
    ]
