# Generated by Django 3.2.8 on 2022-01-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20220107_1454'),
        ('cart', '0005_cartcustomer_cartquantitycustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartquantitycustomer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.resellproduct'),
        ),
    ]
